syntax on                   "语法支持 syn on
set nocompatible            "不要使用vi的键盘模式，而是vim自己的

" common conf {{             通用配置
set autoindent              "自动缩进 set ai
set bs=2                    "在insert模式下用退格键删除
set showmatch               "代码匹配
set laststatus=2            "总是显示状态行
set expandtab               "以下三个配置配合使用，设置tab和缩进空格数
set shiftwidth=4
set tabstop=4
set cursorline              "为光标所在行加下划线
set number                  "显示行号
set autoread                "文件在Vim之外修改过，自动重新读入

set ignorecase              "检索时忽略大小写
"set fileencodings=uft-8,gbk "使用utf-8或gbk打开文件
set hls                     "检索时高亮显示匹配项
set helplang=en             "帮助系统设置为中文
set foldmethod=syntax       "代码折叠
" }}

" autoload _vimrc
autocmd! bufwritepost _vimrc source %

" conf for tabs, 为标签页进行的配置，通过ctrl h/l切换标签等
let mapleader = ','
nnoremap <C-l> gt
nnoremap <C-h> gT
nnoremap <leader>t : tabe<CR>

" For vundle
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'
" My Bundles here:  
" original repos on github
"（Github网站上非vim-scripts仓库的插件，按下面格式填写）  
Bundle 'tpope/vim-fugitive'  
Bundle 'Lokaltog/vim-easymotion'  
Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}  
Bundle 'tpope/vim-rails.git'  
Bundle 'Lokaltog/vim-powerline.git'
"Bundle 'scrooloose/nerdtree'
" vim-scripts repos  （vim-scripts仓库里的，按下面格式填写）  
Bundle "SuperTab"
Bundle "vimwiki"
Bundle 'bash-support.vim'
Bundle 'perl-support.vim'
Bundle 'L9'  
Bundle 'FuzzyFinder'  
"Bundle 'visualMarks.vim' 
Bundle 'winmanager'  
Bundle 'minibufexpl.vim'  
Bundle 'bufexplorer.zip'
Bundle 'OmniCppComplete'  
Bundle 'taglist.vim'  
Bundle 'php-doc'
Bundle 'Xdebug'
Bundle 'skyWeb'
Bundle 'phpunit'
Bundle 'phpcomplete.vim'
Bundle 'php.vim' 
Bundle 'The-NERD-tree'
Bundle 'Vimpress'
Bundle 'Markdown'
Bundle 'snipMate'
"Bundle 'php_check_syntax.vim'
"Bundle 'php_funcinfo.vim'
" non github repos   (非上面两种情况的，按下面格式填写)  
Bundle 'git://git.wincent.com/command-t.git'  
" ...   
filetype plugin indent on     " required!    
" vundle Brief help:  
" :BundleList          - list configured bundles  
" :BundleInstall(!)    - install(update) bundles  
" :BundleSearch(!) foo - search(or refresh cache first) for foo   
" :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles  
" see :h vundle for more details or wiki for FAQ   
" NOTE: comments after Bundle command are not allowed.. 

" conf for plugins {{ 插件相关的配置
" 状态栏的配置 
" powerline{
set nocompatible            "不要使用vi的键盘模式，而是vim自己的
set guifont=PowerlineSymbols\ for\ Powerline
set t_Co=256
let g:Powerline_symbols = 'fancy'
" }
" }}
"taglist{
let Tlist_Show_One_File = 1         "只显示当前文件的taglist，默认是显示多个
let Tlist_Exit_OnlyWindow = 1       "如果taglist是最后一个窗口，则退出vim
let Tlist_Use_left_Window = 1      "在右侧窗口中显示taglist
let Tlist_GainFocus_On_ToggleOpen = 1 "打开taglist时，光标保留在taglist窗口
let Tlist_Ctags_Cmd='/usr/local/bin/ctags' "设置ctags命令的位置
nnoremap <leader>tl : Tlist<CR>     "设置关闭和打开taglist窗口的快捷键
"}
"winmanager{
let g:winManagerWindowLayout='FileExplorer'
nmap wm : WMToggle<cr>
"}
